question_data = [
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In the movie Demon Slayer: Mugen Train, Rengoku dies to Muzan Kibutsuji.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean", "difficulty": "easy",
     "question": "In the second season of Demon Slayer (Entertainment District Arc), Sound Hashira Uzui Tengen has 3 wives.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean","difficulty": "easy",
     "question": "Your Name is the highest grossing Japanese film based on an anime of all time",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean","difficulty": "easy",
     "question": "Saori Hayami, who plays Yor Forger in Spy x Family, also voices Shinobu in Demon Slayer: Kimetsu no Yaiba.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean", "difficulty": "medium",
     "question": "The anime Attack on Titan was directed by Tetsurou Araki, the same person who directed the anime Highschool of the Dead.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Geography",
     "type": "boolean", "difficulty": "easy",
     "question": "The capital of Ecuador is Santiago",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Math",
     "type": "boolean", "difficulty": "easy",
     "question": "There are 351 positive integers between 69 and 420 inclusive",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Video Games/Esports",
     "type": "boolean", "difficulty": "easy",
     "question": "s1mple was the #1 HLTV Player of 2020 for CSGO",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Physics",
     "type": "boolean", "difficulty": "hard",
     "question": "Velocity is a scalar quantity and Speed is a vector quantity",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Physics",
     "type": "boolean", "difficulty": "hard",
     "question": "Albert Einstein is credited with the discovery of the photoelectric effect",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Chemistry",
     "type": "boolean", "difficulty": "medium",
     "question": "Gold has an atomic number of 79 and has the symbol Ag",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Chemistry",
     "type": "boolean", "difficulty": "medium",
     "question": "Nitrogen has 3 bonding electrons in its lewis structure",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music",
  "type": "boolean", "difficulty": "medium",
  "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
  "correct_answer": "True",
  "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games",
  "type": "boolean", "difficulty": "easy",
  "question": "In the Half-Life series, H.E.V stands for Hazardous EnVironment suit",
  "correct_answer": "False",
  "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games",
  "type": "boolean", "difficulty": "medium",
  "question": "David Baszucki was a co-founder of ROBLOX Corporation.",
  "correct_answer": "True",
  "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics",
  "type": "boolean", "difficulty": "easy",
  "question": "The sum of any two odd integers is odd.",
  "correct_answer": "False",
  "incorrect_answers": ["True"]},
    {"category": "Politics",
  "type": "boolean", "difficulty": "easy",
  "question": "Former president Theodore Roosevelt (1900-1908) ran for another term under the Progressive Party in 1912.",
  "correct_answer": "True",
  "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music",
  "type": "boolean", "difficulty": "easy",
  "question": "Some songs written by Ed Sheeran include Shape of You, Afterglow, and Overpass Graffiti",
  "correct_answer": "True",
  "incorrect_answers": ["False"]},
    {"category": "Art",
  "type": "boolean", "difficulty": "hard",
  "question": "The Statue of Liberty's official name is Liberty Enlightening the World",
  "correct_answer": "True",
  "incorrect_answers": ["False"]}
]
